version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.gnosis-beacon-chain-prysm.dnp.dappnode.eth:1.0.4"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.2
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - 12000/udp
      - 13000/tcp
    restart: unless-stopped
    environment:
      WEB3_BACKUP: "https://rpc.gnosischain.com/"
      HTTP_WEB3PROVIDER: "http://nethermind-xdai.dappnode:8545"
      CORSDOMAIN: "http://gnosis-beacon-chain-prysm.dappnode"
      DEPLOYMENT_BLOCK: 19469077
      EXTRA_OPTS: ""
  graffiti:
    image: "graffiti.gnosis-beacon-chain-prysm.dnp.dappnode.eth:1.0.4"
    build:
      context: graffiti
      args:
        UPSTREAM_VERSION: 0.1.2
    volumes:
      - "graffiti-data:/graffiti/"
    restart: unless-stopped
    environment:
      NETWORK: gnosis
      CONSENSUS_CLIENT: prysm
      GRAFFITI_PREFIX: DAppNode
      OUTPUT_FILE: /graffiti/graffiti.txt
      INPUT_URL: >-
        https://raw.githubusercontent.com/stake-house/DecentralizedGraffitiDrawing/main/examples/outputs/colored_eth.json
      EXTRA_OPTS: ""
  validator:
    image: "validator.gnosis-beacon-chain-prysm.dnp.dappnode.eth:1.0.4"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.2
    volumes:
      - "graffiti-data:/root/graffiti/"
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.gnosis-beacon-chain-prysm.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.gnosis-beacon-chain-prysm.dappnode:3500"
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-chain-data: {}
  graffiti-data: {}
  validator-data: {}
